name: Build ROS2 Jazzy Packages

# Pushing to main or PR targeting main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${secrets.SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: "${secrets.SSH_PRIVATE_KEY}"


      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      # Set up ROS2 environment
      - name: Set up ROS2 Jazzy
        uses: ros-tooling/setup-ros@0.7.9
        with:
          version: jazzy
          install-source: false # Set to true if you want to install from source

      # Install ROS2 dependencies
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      # Build the ROS2 workspace
      - name: Build workspace
        run: |
          colcon build --base-paths .

      # Run tests (optional)
      - name: Run tests
        run: |
          colcon test --base-paths .
          colcon test-result --verbose
