name: Build ROS2 Jazzy Packages

# Pushing to main or PR targeting main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  colcon_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: "${{secrets.SSH_PRIVATE_KEY}}"
          fetch-depth: 0

      # Set up ROS2 environment
      - name: Set up ROS2 Jazzy
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: jazzy
          use-ros2-testing: true
      - run: source /opt/ros/jazzy/setup.bash
          
          # Install ROS2 dependencies
      - name: Install ROS dependencies
        run: |
            export ROS_DISTRO=jazzy
            rosdep update --rosdistro jazzy
            rosdep install --from-paths . --ignore-src -r -y
      
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: 'jazzy'


      # # Build the ROS2 workspace
      # - name: Build ROS2 workspace with colcon
      #   run: |
      #     colcon build --base-paths .

      # # Run tests (optional)
      # - name: Test ROS2 workspace with colcon
      #   run: |
      #     colcon test --base-paths . --event-handlers console_direct+ log+
      #     colcon test-result --verbose --event-handlers console_direct+ log+ 
