name: Build Workspace

# Pushing to main or PR targeting main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble

    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install ssh

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: "${{secrets.SSH_PRIVATE_KEY}}"
      
      - name: Update Git Submodules
        run: git submodule update --init --recursive

      # Set up ROS2 environment
      - name: Setup ROS2 Jazzy
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: jazzy

      - name: Install ROS dependencies
        run: |
            export ROS_DISTRO=jazzy
            source /opt/ros/jazzy/setup.bash
            rosdep update --rosdistro jazzy
            rosdep install --from-paths . --ignore-src -r -y
      
      - name: Colcon Build
        run: |
            colcon build --base-paths .
      
      # - name: Build and Test
      #   uses: ros-tooling/action-ros-ci@v0.3
      #   with:
      #     target-ros2-distro: 'jazzy'
